AWSTemplateFormatVersion: '2010-09-09'
Resources:


  ##########################################################################################################################
  # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  ##########################################################################################################################
  WebContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  ##########################################################################################################################
  # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-cloudfrontoriginaccessidentity.html
  ##########################################################################################################################
  CloudFrontDistributionAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CDN Identity Access


  ##########################################################################################################################
  # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
  ##########################################################################################################################
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt 
            - WebContentBucket
            - DomainName
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Join 
              - ''
              - - 'origin-access-identity/cloudfront/'
                - !GetAtt 
                  - CloudFrontDistributionAccessIdentity
                  - Id
        Enabled: 'true'
        Comment: Some comment
        DefaultRootObject: index.html
        # Logging:
        #   IncludeCookies: 'false'
        #   Bucket: mylogs.s3.amazonaws.com
        #   Prefix: myprefix
        # Aliases:
        # - mysite.example.com
        # - yoursite.example.com
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          # TrustedSigners:
          # - 1234567890EX
          # - 1234567891EX
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_200
        # Restrictions:
        #   GeoRestriction:
        #     RestrictionType: whitelist
        #     Locations:
        #     - AQ
        #     - CV
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'

  ##########################################################################################################################
  # Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html
  ##########################################################################################################################
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebContentBucket
                - /*

          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal: 
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebContentBucket
                - /*
            Condition:
              StringEquals:
                'AWS:SourceArn':  !Join 
                  - ''
                  - - 'arn:aws:cloudfront::'
                    - !Ref 'AWS::AccountId'
                    - ':distribution/'
                    - !Ref CloudFrontDistribution

      Bucket: !Ref WebContentBucket

Outputs:

  S3UploadCommand:
    Value: !Join 
      - ''
      - - 'aws s3 sync . s3://'
        - !Ref WebContentBucket

  S3RemoveCommand:
    Value: !Join 
      - ''
      - - 'aws s3 rm s3://'
        - !Ref WebContentBucket
        - ' --recursive'

  WebsiteURL:
    Value: !GetAtt 
      - WebContentBucket
      - WebsiteURL

  CloudFrontUrl:
    Value: !GetAtt 
      - CloudFrontDistribution
      - DomainName
  